name: Consistency Tests

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.10']
        nvim-tag: [stable]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: Install tree-sitter CLI
        run: npm i -g tree-sitter

      - name: Prepare Nvim
        env:
          NVIM_TAG: ${{ matrix.nvim-tag }}
        run: |
          sudo apt-get update && sudo apt-get install libfuse2
          sudo add-apt-repository universe
          wget https://github.com/neovim/neovim/releases/download/${NVIM_TAG}/nvim.appimage
          chmod u+x nvim.appimage && sudo mv nvim.appimage /usr/local/bin/nvim
          mkdir -p ~/.local/share/nvim/site/pack/nvim-treesitter-textobject/opt
          ln -s $(pwd) ~/.local/share/nvim/site/pack/nvim-treesitter-textobject/opt
          mkdir -p ~/.local/share/nvim/site/pack/nvim-treesitter/opt
          cd ~/.local/share/nvim/site/pack/nvim-treesitter/opt
          git clone https://github.com/nvim-treesitter/nvim-treesitter.git
      - name: Compile parsers
        run: nvim --headless -c "packadd nvim-treesitter" -c "TSInstallSync all" -c "q"

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          cd scripts/python_tests && pip install -e .
      - name: Test
        run: cd scripts/python_tests/tools && bash download_and_run_tests.sh || exit 1
