name: Linting and style checking

on: pull_request

jobs:
  luacheck:
    name: Luacheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Prepare
        run: |
          sudo apt-get update
          sudo add-apt-repository universe
          sudo apt install luarocks -y
          sudo luarocks install luacheck

      - name: Run Luacheck
        run: sudo ./scripts/style-check.sh

  stylua:
    name: StyLua
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Lint with stylua
      uses: JohnnyMorganz/stylua-action@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        version: latest
        args: --check .

  format-queries:
    name: Lint queries
    runs-on: ubuntu-latest
    env:
      NVIM_TAG: stable
    steps:
      - uses: actions/checkout@v4
      - name: Prepare
        run: |
          bash ./scripts/ci-install-ubuntu-latest.sh
          wget -P scripts/ https://raw.githubusercontent.com/nvim-treesitter/nvim-treesitter/main/scripts/format-queries.lua
          mkdir -p ~/.local/share/nvim/site/pack/nvim-treesitter/start
          cd ~/.local/share/nvim/site/pack/nvim-treesitter/start
          git clone https://github.com/nvim-treesitter/nvim-treesitter.git

      - name: Lint
        run: |
          nvim --headless -c "TSInstallSync query" -c "q"
          nvim -l scripts/format-queries.lua queries
          git diff --exit-code
